version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5433:5432"
    networks:
      - production-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
      - "16543:80"
    networks:
      - production-network
    depends_on:
      - postgres

  microservice-propostas:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: nfrederico/microservice-propostas
    container_name: microservice-propostas
    ports:
      - "8085:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/root
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - production-network
    depends_on:
      - postgres

networks:
  production-network:
    external: true
